### ISSUE TITLE
new roles in ARIA 1.1

### ISSUE THREAD

**Issue by stevefaulkner** [dylanb/dylanb.github.io#1]
text http://rawgit.com/w3c/aria/master/aria/aria.html#text
searchbox http://rawgit.com/w3c/aria/master/aria/aria.html#searchbox
switch http://rawgit.com/w3c/aria/master/aria/aria.html#switch
none http://rawgit.com/w3c/aria/master/aria/aria.html#none

**Comment by dylanb** [comment]
Awesome - thanks Steve, I will add these
