### ISSUE TITLE
focus issue with ios

### ISSUE THREAD

**Issue by goetsu** [dylanb/dylanb.github.io#3]
Hi, I have found this page http://dylanb.github.io/bower_components/a11yfy/examples/focus.html and it appear that the bug isn't totally fixed is iOS. In some case, you still need a setTimeout to 0.
Here is an example : 
http://codepen.io/goetsu/pen/yymmLQ  

In that case when the buttons get focused I want to move it to the link just after it (sound strange I know but for example it can be useful in some more realistic case like moving focus back to the start of a modale windows when you reach the end.

**Comment by dylanb** [comment]
Thanks - I will investigate

**Comment by dylanb** [comment]
Fixed in https://github.com/dylanb/dylanb.github.io/commit/37509f8460617922ca0ab7400ea5eff369112ec0
