### ISSUE TITLE
periodic-aria-attributes.html popup is empty

### ISSUE THREAD

**Issue by Scratch2k** [dylanb/dylanb.github.io#4]
The popup modal appears with nothing but a 'close' button, no link to the bookmark in the spec page. Why not just link to the spec page directly from each 'element'?

**Comment by Scratch2k** [comment]
![image](https://cloud.githubusercontent.com/assets/9923510/7742026/1fd81888-ffcc-11e4-9b7f-6040868b1366.png)

Console is reporting:

> XMLHttpRequest cannot load http://www.w3.org/TR/wai-aria/states_and_properties. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.

(testing this from codepen, but it behaves the same on your host)

This explains why the remote page isn't loading, the w3 doesn't like cross-origin loading, investigating.

**Comment by dylanb** [comment]
Works fine for me and I have had other people report being able to use it fine. There must be something else going on ![image](https://cloud.githubusercontent.com/assets/79245/7749917/eb600624-ff9e-11e4-9009-6143bc651c37.png)
